### ISSUE TITLE
Connect to spawned server

### ISSUE THREAD

**Issue by phoboslab** [kesla/node-headless#19]
Pardon my ignorance. I can't figure out how to actually connect to the spawned server. I've been previously using (without nodejs) `xvfb-run -a some-binary` – how would I translate that to this library?

I've tried the following
```js
var headless = require('headless'),
var exec = require('child_process').exec;

headless(function(err, childProcess, servernum) {
	exec('xvfb-run -n '+ servernum + ' some-binary', error, stdout, stderr) {
		console.log('stdout:', stdout);
		console.log('stderr:', stderr);
		
		// kill the xvfb server - is this the correct place to do this?
		childProcess.kill();
	});
});
```
But this only emits `"error: Xvfb failed to start"`, as if servernum were invalid.

**Comment by kesla** [comment]
headless will start the xvfb instance so no need to do the `exec('xvfb-run...` stuff.

The servernum is invalid since there's been a server opened w that servernum already from the headless library.

**Comment by phoboslab** [comment]
So I just do `exec('some-binary)` inside the `headless()` callback? Wow, sorry, that didn't cross my mind.

Thank you!
