### ISSUE TITLE
Pass arbitrary arguments to Xvfb?

### ISSUE THREAD

**Issue by paulkernfeld** [kesla/node-headless#20]
Hey guys,

This is a great package! I'm currently seeing [an error](https://github.com/mappum/electron-eval/pull/43) in the electron-eval project, which depends on this. StackOverflow [seems to think](http://stackoverflow.com/questions/17944234/xlib-extension-randr-missing-on-display-21-trying-to-run-headless-googl) that this can be solved by adding some CLI args to Xvfb, although I'm not sure which ones exactly. Could I make a PR that allows the user to specify custom CLI args for Xvfb? Does anyone have an opinion on the interface?

**Comment by kesla** [comment]
Hey @paulkernfeld!

Thanks for the kind words.

Yes, let's add that. Would be great! I don't have any specific idea on the interface, you'll figure it out :)

**Comment by kesla** [comment]
Closed by #21
